-- Example custom keybinding in your AstroNvim config:
return {}
--   "folke/snacks.nvim",
--   opts = {
--     picker = {
--       -- you can define a new literal search picker
--     },
--   },
--   -- define a custom keymap
--   config = function()
--     vim.keymap.set("n", "<leader>f<C-W>", function()
--       Snacks.picker.grep({
--         search = vim.fn.input("Literal search term: "),
--         live = false,       -- turn off live mode for manual controls
--         args = { "--fixed-strings" },
--         finder = "grep",
--         format = "file",
--       })
--     end, { desc = "Literal grep (fixed string)" })
--   end,
-- }
